import { GAME, PARTICIPATION } from "$lib/ergo/reputation/types";

export interface GameConstants {
    JUDGE_PERIOD: number;
    CREATOR_OMISSION_NO_PENALTY_PERIOD: number;
    MAX_SCORE_LIST: number;
    DEV_COMMISSION_PERCENTAGE: number;
    STAKE_DENOMINATOR: number;
    COOLDOWN_IN_BLOCKS: number;
    PARTICIPATION_ABANDONED_FUNDS_GRACE_PERIOD: number;
    PARTICIPATION_GRACE_PERIOD_IN_BLOCKS: number;
    OPEN_CEREMONY_BLOCKS: number;

    PARTICIPATION_TYPE_ID: string;
    ACCEPT_GAME_INVITATION_TYPE_ID: string;
    DEV_SCRIPT: string;
}

export const DefaultGameConstants: GameConstants = {
    JUDGE_PERIOD: 30,
    CREATOR_OMISSION_NO_PENALTY_PERIOD: 5,
    MAX_SCORE_LIST: 10,
    DEV_COMMISSION_PERCENTAGE: 5,
    STAKE_DENOMINATOR: 5,
    COOLDOWN_IN_BLOCKS: 30,
    PARTICIPATION_ABANDONED_FUNDS_GRACE_PERIOD: 64800,
    PARTICIPATION_GRACE_PERIOD_IN_BLOCKS: 720,
    PARTICIPATION_TYPE_ID: PARTICIPATION,
    ACCEPT_GAME_INVITATION_TYPE_ID: GAME,
    DEV_SCRIPT: "0008cd025ac8ab183ffde36068603120b00acdf141b91fe4e0c0c6d562b5f24e1e2cc2d1",
    OPEN_CEREMONY_BLOCKS: 20
};