import { GAME, PARTICIPATION } from "$lib/ergo/reputation/types";

export interface GameConstants {
    JUDGE_PERIOD: number;    // VARIOS BLOQUES PARA PERMITIR A TODOS LOS JUECES PROBAR EL CANDIDATO.
    CREATOR_OMISSION_NO_PENALTY_PERIOD: number;  // VARIOS BLOQUES PARA NO PERMITIR QUE SE MODFIQUE EL RESOLVER. // Must be less than JUDGE_PERIOD, but the difference must be enough to allow others penalize creator after this period.
    MAX_SCORE_LIST: number;
    DEV_COMMISSION_PERCENTAGE: number;
    STAKE_DENOMINATOR: number;
    COOLDOWN_IN_BLOCKS: number;
    END_GAME_AUTH_GRACE_PERIOD: number;   // A PARTIR DE RESOLUTION DEADLINE (R8.5)
    PARTICIPATION_GRACE_PERIOD_IN_BLOCKS: number;    // A PARTIR DE DEADLINE (R8.0) - TIEMPO QUE TIENE EL CREADOR PARA REVELAR EL SECRETO
    OPEN_CEREMONY_BLOCKS: number;  // DEBE SER MENOR QUE DEADLINE

    PARTICIPATION_TYPE_ID: string;
    ACCEPT_GAME_INVITATION_TYPE_ID: string;
    DEV_SCRIPT: string;
}

const DevelopmentMode: GameConstants = {
    JUDGE_PERIOD: 20,  // aprox 40 minutes para permitir agregar varias participaciones.
    CREATOR_OMISSION_NO_PENALTY_PERIOD: 5,
    MAX_SCORE_LIST: 10,
    DEV_COMMISSION_PERCENTAGE: 5,
    STAKE_DENOMINATOR: 5,
    COOLDOWN_IN_BLOCKS: 30,
    END_GAME_AUTH_GRACE_PERIOD: 5,
    PARTICIPATION_GRACE_PERIOD_IN_BLOCKS: 5,
    OPEN_CEREMONY_BLOCKS: 5,  // Suficiente para probar

    PARTICIPATION_TYPE_ID: PARTICIPATION,
    ACCEPT_GAME_INVITATION_TYPE_ID: GAME,
    DEV_SCRIPT: "0008cd025ac8ab183ffde36068603120b00acdf141b91fe4e0c0c6d562b5f24e1e2cc2d1",
};

const ProductionMode: GameConstants = {
    JUDGE_PERIOD: 720,  // aprox. one day
    CREATOR_OMISSION_NO_PENALTY_PERIOD: 5,
    MAX_SCORE_LIST: 10,
    DEV_COMMISSION_PERCENTAGE: 5,
    STAKE_DENOMINATOR: 5,
    COOLDOWN_IN_BLOCKS: 30,
    END_GAME_AUTH_GRACE_PERIOD: 64800,  // aprox. 90 days
    PARTICIPATION_GRACE_PERIOD_IN_BLOCKS: 720,  // aprox. one day
    OPEN_CEREMONY_BLOCKS: 720,  // aprox. one day

    PARTICIPATION_TYPE_ID: PARTICIPATION,
    ACCEPT_GAME_INVITATION_TYPE_ID: GAME,
    DEV_SCRIPT: "0008cd025ac8ab183ffde36068603120b00acdf141b91fe4e0c0c6d562b5f24e1e2cc2d1"
}

export const DefaultGameConstants: GameConstants = DevelopmentMode;