import { GAME, PARTICIPATION, PARTICIPATION_UNAVAILABLE } from "$lib/ergo/reputation/types";

export interface GameConstants {
    JUDGE_PERIOD: number;    // VARIOS BLOQUES PARA PERMITIR A TODOS LOS JUECES PROBAR EL CANDIDATO.
    RESOLVER_OMISSION_NO_PENALTY_PERIOD: number;  // VARIOS BLOQUES PARA NO PERMITIR QUE SE MODFIQUE EL RESOLVER. // Must be less than JUDGE_PERIOD, but the difference must be enough to allow others penalize resolver after this period.
    MAX_SCORE_LIST: number;
    DEV_COMMISSION_PERCENTAGE: number;
    STAKE_DENOMINATOR: number;
    COOLDOWN_IN_BLOCKS: number;
    END_GAME_AUTH_GRACE_PERIOD: number;   // A PARTIR DE RESOLUTION DEADLINE (R8.5)
    PARTICIPATION_GRACE_PERIOD_IN_BLOCKS: number;    // A PARTIR DE DEADLINE (R8.0) - TIEMPO QUE TIENE EL RESOLVER PARA REVELAR EL SECRETO
    PARTICIPATION_TIME_WINDOW: number;
    SEED_MARGIN: number;

    PARTICIPATION_TYPE_ID: string;
    PARTICIPATION_UNAVAILABLE_TYPE_ID: string;
    ACCEPT_GAME_INVITATION_TYPE_ID: string;
    DEV_SCRIPT: string;
    COMMISSION_DENOMINATOR: number;
}

const DevelopmentMode: GameConstants = {
    JUDGE_PERIOD: 5,
    RESOLVER_OMISSION_NO_PENALTY_PERIOD: 5,
    MAX_SCORE_LIST: 10,
    DEV_COMMISSION_PERCENTAGE: 5,
    STAKE_DENOMINATOR: 5,
    COOLDOWN_IN_BLOCKS: 30,
    END_GAME_AUTH_GRACE_PERIOD: 5,
    PARTICIPATION_GRACE_PERIOD_IN_BLOCKS: 5,
    PARTICIPATION_TIME_WINDOW: 10,
    SEED_MARGIN: 5,

    PARTICIPATION_TYPE_ID: PARTICIPATION,
    PARTICIPATION_UNAVAILABLE_TYPE_ID: PARTICIPATION_UNAVAILABLE,
    ACCEPT_GAME_INVITATION_TYPE_ID: GAME,
    DEV_SCRIPT: "0008cd025ac8ab183ffde36068603120b00acdf141b91fe4e0c0c6d562b5f24e1e2cc2d1",
    COMMISSION_DENOMINATOR: 1000000,  // Hardcoded conversion.
};

const ProductionMode: GameConstants = {
    JUDGE_PERIOD: 720,  // aprox. one day
    RESOLVER_OMISSION_NO_PENALTY_PERIOD: 5,
    MAX_SCORE_LIST: 10,
    DEV_COMMISSION_PERCENTAGE: 5,
    STAKE_DENOMINATOR: 5,
    COOLDOWN_IN_BLOCKS: 30,
    END_GAME_AUTH_GRACE_PERIOD: 64800,  // aprox. 90 days
    PARTICIPATION_GRACE_PERIOD_IN_BLOCKS: 2160,  // aprox. three days
    PARTICIPATION_TIME_WINDOW: 4320, // aprox. 6 days
    SEED_MARGIN: 20,

    PARTICIPATION_TYPE_ID: PARTICIPATION,
    PARTICIPATION_UNAVAILABLE_TYPE_ID: PARTICIPATION_UNAVAILABLE,
    ACCEPT_GAME_INVITATION_TYPE_ID: GAME,
    DEV_SCRIPT: "0008cd025ac8ab183ffde36068603120b00acdf141b91fe4e0c0c6d562b5f24e1e2cc2d1",
    COMMISSION_DENOMINATOR: 1000000,  // Hardcoded conversion.
}



import { get } from "svelte/store";
import { isDevMode } from "$lib/ergo/envs";

export const getGameConstants = (): GameConstants => {
    return get(isDevMode) ? DevelopmentMode : ProductionMode;
};

// Export for tests
export const DefaultGameConstants = ProductionMode;